// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD94rrYtZPIP2ou2yWyEx9zfmhrFKw-ATQ',
    appId: '1:707456573917:web:5bc7ccab0a8f66c6fd9634',
    messagingSenderId: '707456573917',
    projectId: 'movies-app-e632d',
    authDomain: 'movies-app-e632d.firebaseapp.com',
    storageBucket: 'movies-app-e632d.firebasestorage.app',
    measurementId: 'G-E5SWWPZ8LH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXOIq2tS41JdQlstsXGul6MnvQQtPG4dk',
    appId: '1:707456573917:android:69ceca99fb7e6624fd9634',
    messagingSenderId: '707456573917',
    projectId: 'movies-app-e632d',
    storageBucket: 'movies-app-e632d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMDYhkKANySAMGASEssTUjFDcUy9r5I_s',
    appId: '1:707456573917:ios:bebe2cacb10dbc35fd9634',
    messagingSenderId: '707456573917',
    projectId: 'movies-app-e632d',
    storageBucket: 'movies-app-e632d.firebasestorage.app',
    iosClientId: '707456573917-5b1s9r9u0s7m5ghunjt8tenlf0hbv6lq.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD94rrYtZPIP2ou2yWyEx9zfmhrFKw-ATQ',
    appId: '1:707456573917:web:80fecd50281abf0afd9634',
    messagingSenderId: '707456573917',
    projectId: 'movies-app-e632d',
    authDomain: 'movies-app-e632d.firebaseapp.com',
    storageBucket: 'movies-app-e632d.firebasestorage.app',
    measurementId: 'G-66BTFJBZTV',
  );
}
